### ISSUE TITLE
[Quest Bug]訓練師的秘方

### ISSUE THREAD

**Issue by ches4117** [TMS-v113/server#25]
- 名稱：訓練師的秘方

- NPC：寵物訓練師巴特斯

- 地點：弓箭手村寵物公園
  
- ID：100000202

- 座標：(-2118 , 236)

- 描述：完成前置任務＂證明身為訓練師的能力＂應該要出現該任務，但是完成前置任務後並沒有出現該任務，且就算拿著寵物點心依然無法觸發該任務。

**Comment by BePsvPT** [comment]
fixed
