### ISSUE TITLE
法師三轉

### ISSUE THREAD

**Issue by bemyself0318** [TMS-v113/server#27]
名稱：沒有名稱

NPC：達克魯

地點：魔法森林圖書館

ID：103000003

座標：( 173 , 96)

描述：
正常流程：
1.天空之城 / 冰原雪域 / 長老公館 / 找NPC三轉教官對話
2.返回維多利亞島 / 魔法森林 / 圖書館 / 找NPC漢斯對話 、接受任務得知必須打倒漢斯分身
3.分身在:次元裂縫 巫婆森林II，水晶道路往前直進入異次元世界，發現漢斯分身，限時20分鐘內打倒取得黑符，點選光明水晶回魔法森林，給予漢斯"黑符"，可獲得"力量項鏈"
4.取得力氣項鏈，回冰原雪域找法師長老對話，他會要求你接受智慧的考驗
異常：
2、3號流程消失，直接從1跳到4，漢斯叫我拿this(力量項鍊)給長老，但也沒給我，長老說我沒力量項鍊，完全卡住，兩個人在踢皮球

**Comment by BePsvPT** [comment]
fixes 8fb9c70
