### ISSUE TITLE
[System Bug] 使用持續性增加 HP 物品，死亡後，血量條顯示異常

### ISSUE THREAD

**Issue by Lyrisbee** [TMS-v113/server#29]
## 物品 Item

- 名稱：緞帶肥肥的御守

- 類別：增加50%HP、25%MP ，持續 1 小時

- 描述：死亡後，最大HP並非使用道具後的血量，是使用前的血量，但是補品可以補到使用道具後的血量，造成血量條超過血量框，同魔力。

**Comment by BePsvPT** [comment]
fixed by #40

**Comment by BePsvPT** [comment]
fixed #40

**Comment by BePsvPT** [comment]
fixed by #40
